# Contact.create!([
#   {first_name: "Randal", last_name: "Koss", email: "koss.randal@gmail.com", phone_number: "1-585-538-5146", middle_name: nil, bio: nil},
#   {first_name: "Dasia", last_name: "Bechtelar", email: "dasia.bechtelar@gmail.com", phone_number: "1-263-425-4858", middle_name: nil, bio: nil},
#   {first_name: "Yazmin", last_name: "Kling", email: "kling_yazmin@gmail.com", phone_number: "1-913-253-4381", middle_name: nil, bio: nil},
#   {first_name: "Celestine", last_name: "Gerhold", email: "gerhold_celestine@gmail.com", phone_number: "1-769-548-0641 x60505", middle_name: nil, bio: nil},
#   {first_name: "Haleigh", last_name: "Keebler", email: "keebler.haleigh@gmail.com", phone_number: "(311) 773-6712 x8108", middle_name: nil, bio: nil},
#   {first_name: "Santa", last_name: "Corwin", email: "santa_corwin@hotmail.com", phone_number: "302.615.4118 x62864", middle_name: nil, bio: nil},
#   {first_name: "Frankie", last_name: "Ferry", email: "frankie.ferry@gmail.com", phone_number: "1-841-913-8463 x1308", middle_name: nil, bio: nil},
#   {first_name: "Gabe", last_name: "Schneider", email: "gabe_schneider@yahoo.com", phone_number: "(538) 988-5517 x13274", middle_name: nil, bio: nil},
#   {first_name: "Sylvester", last_name: "Baumbach", email: "sylvester_baumbach@yahoo.com", phone_number: "1-524-231-9213 x291", middle_name: nil, bio: nil},
#   {first_name: "Thea", last_name: "Cormier", email: "thea.cormier@gmail.com", phone_number: "722-198-6912", middle_name: nil, bio: nil},
#   {first_name: "Liam", last_name: "Hilpert", email: "hilpert_liam@gmail.com", phone_number: "1-913-656-6655 x37697", middle_name: nil, bio: nil},
#   {first_name: "Christophe", last_name: "Kuhlman", email: "christophe.kuhlman@hotmail.com", phone_number: "525-200-4338", middle_name: nil, bio: nil},
#   {first_name: "Wilfred", last_name: "Swaniawski", email: "swaniawski_wilfred@gmail.com", phone_number: "571-518-6623", middle_name: nil, bio: nil},
#   {first_name: "Guido", last_name: "O'Kon", email: "o_kon_guido@yahoo.com", phone_number: "436.916.8617", middle_name: nil, bio: nil},
#   {first_name: "Brody", last_name: "Nitzsche", email: "nitzsche_brody@hotmail.com", phone_number: "(526) 535-4220", middle_name: nil, bio: nil},
#   {first_name: "Deon", last_name: "Kuhn", email: "deon.kuhn@gmail.com", phone_number: "498-013-9948 x84435", middle_name: nil, bio: nil},
#   {first_name: "Marcelino", last_name: "Beier", email: "beier_marcelino@gmail.com", phone_number: "1-525-987-3160 x125", middle_name: nil, bio: nil},
#   {first_name: "Kaia", last_name: "Senger", email: "kaia_senger@yahoo.com", phone_number: "425.830.2381", middle_name: nil, bio: nil},
#   {first_name: "Everette", last_name: "Witting", email: "witting.everette@yahoo.com", phone_number: "239.587.6884", middle_name: nil, bio: nil},
#   {first_name: "Otha", last_name: "Champlin", email: "otha_champlin@gmail.com", phone_number: "(266) 188-0829", middle_name: nil, bio: nil},
#   {first_name: "Aida", last_name: "Sporer", email: "aida_sporer@hotmail.com", phone_number: "659.370.7398", middle_name: nil, bio: nil},
#   {first_name: "Merle", last_name: "Wolff", email: "wolff.merle@yahoo.com", phone_number: "496.121.3129", middle_name: nil, bio: nil},
#   {first_name: "Cynthia", last_name: "Littel", email: "littel_cynthia@gmail.com", phone_number: "(911) 982-4031 x8822", middle_name: nil, bio: nil},
#   {first_name: "Kadin", last_name: "Block", email: "block_kadin@yahoo.com", phone_number: "608.133.2022", middle_name: nil, bio: nil},
#   {first_name: "Adolfo", last_name: "Wisoky", email: "adolfo.wisoky@gmail.com", phone_number: "1-316-968-7324", middle_name: nil, bio: nil},
#   {first_name: "Rowan", last_name: "Gleichner", email: "gleichner.rowan@gmail.com", phone_number: "759.224.9299 x252", middle_name: nil, bio: nil},
#   {first_name: "Carrie", last_name: "Feeney", email: "carrie.feeney@yahoo.com", phone_number: "1-384-339-5131 x64627", middle_name: nil, bio: nil},
#   {first_name: "Sabrina", last_name: "Sipes", email: "sabrina.sipes@gmail.com", phone_number: "(910) 583-2374 x89856", middle_name: nil, bio: nil},
#   {first_name: "Anabelle", last_name: "Tromp", email: "tromp.anabelle@hotmail.com", phone_number: "(793) 982-3650 x6052", middle_name: nil, bio: nil},
#   {first_name: "Maurine", last_name: "Streich", email: "maurine.streich@hotmail.com", phone_number: "186-277-4094 x155", middle_name: nil, bio: nil},
#   {first_name: "Keira", last_name: "Ward", email: "keira.ward@yahoo.com", phone_number: "579.007.5902 x11572", middle_name: nil, bio: nil},
#   {first_name: "Jewel", last_name: "MacGyver", email: "macgyver_jewel@hotmail.com", phone_number: "1-856-265-8509 x8918", middle_name: nil, bio: nil},
#   {first_name: "Wallace", last_name: "Schroeder", email: "wallace.schroeder@hotmail.com", phone_number: "851-532-9493", middle_name: nil, bio: nil},
#   {first_name: "Estel", last_name: "Denesik", email: "estel_denesik@gmail.com", phone_number: "(571) 497-5277 x806", middle_name: nil, bio: nil},
#   {first_name: "Dedric", last_name: "Gleason", email: "dedric_gleason@yahoo.com", phone_number: "(964) 764-3645 x031", middle_name: nil, bio: nil},
#   {first_name: "Stefan", last_name: "Franecki", email: "franecki_stefan@hotmail.com", phone_number: "414-104-2218 x047", middle_name: nil, bio: nil},
#   {first_name: "Odessa", last_name: "Steuber", email: "odessa.steuber@hotmail.com", phone_number: "280-456-9703 x064", middle_name: nil, bio: nil},
#   {first_name: "Niko", last_name: "Moen", email: "moen.niko@yahoo.com", phone_number: "1-499-241-0823 x1231", middle_name: nil, bio: nil},
#   {first_name: "Golden", last_name: "Bogan", email: "golden_bogan@gmail.com", phone_number: "508.682.6879 x00657", middle_name: nil, bio: nil},
#   {first_name: "Joesph", last_name: "Ondricka", email: "joesph.ondricka@yahoo.com", phone_number: "(188) 906-2887", middle_name: nil, bio: nil},
#   {first_name: "Wilhelm", last_name: "Lakin", email: "lakin_wilhelm@hotmail.com", phone_number: "394-467-7449 x066", middle_name: nil, bio: nil},
#   {first_name: "Tiffany", last_name: "Kulas", email: "tiffany_kulas@yahoo.com", phone_number: "131.749.1753", middle_name: nil, bio: nil},
#   {first_name: "Marcelina", last_name: "Murphy", email: "marcelina.murphy@hotmail.com", phone_number: "284-193-3646", middle_name: nil, bio: nil},
#   {first_name: "Shanna", last_name: "Roberts", email: "shanna.roberts@hotmail.com", phone_number: "(467) 277-5783 x69843", middle_name: nil, bio: nil},
#   {first_name: "Tom", last_name: "Steuber", email: "steuber.tom@hotmail.com", phone_number: "(782) 641-2428 x943", middle_name: nil, bio: nil},
#   {first_name: "Clemens", last_name: "Wolf", email: "wolf_clemens@hotmail.com", phone_number: "485-094-4665", middle_name: nil, bio: nil},
#   {first_name: "Jackeline", last_name: "Stehr", email: "jackeline.stehr@yahoo.com", phone_number: "1-234-132-6720 x285", middle_name: nil, bio: nil},
#   {first_name: "Johann", last_name: "Gislason", email: "gislason.johann@yahoo.com", phone_number: "(432) 788-2832 x56867", middle_name: nil, bio: nil},
#   {first_name: "Jaleel", last_name: "Sporer", email: "sporer_jaleel@gmail.com", phone_number: "1-108-125-4924 x2915", middle_name: nil, bio: nil},
#   {first_name: "Buck", last_name: "Considine", email: "buck_considine@gmail.com", phone_number: "772-459-1164 x21123", middle_name: nil, bio: nil},
#   {first_name: "Katlyn", last_name: "Padberg", email: "padberg.katlyn@hotmail.com", phone_number: "1-346-006-1512 x1804", middle_name: nil, bio: nil},
#   {first_name: "Myrtice", last_name: "Franecki", email: "franecki_myrtice@yahoo.com", phone_number: "692.225.8490 x05341", middle_name: nil, bio: nil},
#   {first_name: "Wade", last_name: "Murphy", email: "wade.murphy@yahoo.com", phone_number: "1-221-209-3271 x461", middle_name: nil, bio: nil},
#   {first_name: "Hobart", last_name: "Erdman", email: "hobart.erdman@yahoo.com", phone_number: "1-587-273-5279 x9887", middle_name: nil, bio: nil},
#   {first_name: "Rowland", last_name: "Becker", email: "becker.rowland@hotmail.com", phone_number: "(301) 840-1250 x585", middle_name: nil, bio: nil},
#   {first_name: "Kyra", last_name: "Koepp", email: "koepp.kyra@gmail.com", phone_number: "(899) 837-8567 x20929", middle_name: nil, bio: nil},
#   {first_name: "Dylan", last_name: "Lehner", email: "dylan.lehner@gmail.com", phone_number: "867-442-5225 x2079", middle_name: nil, bio: nil},
#   {first_name: "Gabriel", last_name: "Homenick", email: "homenick.gabriel@yahoo.com", phone_number: "733-336-0991", middle_name: nil, bio: nil},
#   {first_name: "Amya", last_name: "Leuschke", email: "leuschke.amya@yahoo.com", phone_number: "728.123.5741 x18460", middle_name: nil, bio: nil},
#   {first_name: "Cecil", last_name: "Boyer", email: "cecil.boyer@yahoo.com", phone_number: "450.858.2387 x795", middle_name: nil, bio: nil},
#   {first_name: "Bertha", last_name: "Cummerata", email: "cummerata.bertha@yahoo.com", phone_number: "554-058-7627", middle_name: nil, bio: nil},
#   {first_name: "Nichole", last_name: "Miller", email: "miller.nichole@gmail.com", phone_number: "768.994.2451", middle_name: nil, bio: nil},
#   {first_name: "Demarco", last_name: "Boehm", email: "boehm_demarco@hotmail.com", phone_number: "812-707-5873 x7180", middle_name: nil, bio: nil},
#   {first_name: "Montana", last_name: "Bauch", email: "montana.bauch@hotmail.com", phone_number: "683.113.4468", middle_name: nil, bio: nil},
#   {first_name: "Amaya", last_name: "Grady", email: "grady.amaya@gmail.com", phone_number: "1-532-583-6682", middle_name: nil, bio: nil},
#   {first_name: "Thurman", last_name: "Gislason", email: "thurman_gislason@yahoo.com", phone_number: "1-913-316-2115 x05786", middle_name: nil, bio: nil},
#   {first_name: "Geovany", last_name: "Terry", email: "terry_geovany@hotmail.com", phone_number: "356-093-5159 x4819", middle_name: nil, bio: nil},
#   {first_name: "Duncan", last_name: "D'Amore", email: "duncan.amore.d@yahoo.com", phone_number: "(829) 733-4351 x06239", middle_name: nil, bio: nil},
#   {first_name: "Rosalyn", last_name: "Hammes", email: "hammes.rosalyn@gmail.com", phone_number: "118.149.1797", middle_name: nil, bio: nil},
#   {first_name: "Kian", last_name: "Ziemann", email: "ziemann_kian@gmail.com", phone_number: "1-387-170-5619", middle_name: nil, bio: nil},
#   {first_name: "Ernestina", last_name: "Powlowski", email: "ernestina_powlowski@hotmail.com", phone_number: "345.295.5279", middle_name: nil, bio: nil},
#   {first_name: "Madisyn", last_name: "Fadel", email: "fadel.madisyn@gmail.com", phone_number: "1-655-891-9343", middle_name: nil, bio: nil},
#   {first_name: "Paula", last_name: "Gleason", email: "paula.gleason@yahoo.com", phone_number: "1-327-668-8664 x22043", middle_name: nil, bio: nil},
#   {first_name: "Rachelle", last_name: "Kiehn", email: "rachelle_kiehn@gmail.com", phone_number: "684.927.1186 x38333", middle_name: nil, bio: nil},
#   {first_name: "Lydia", last_name: "McLaughlin", email: "lydia_mclaughlin@yahoo.com", phone_number: "448-022-7337 x937", middle_name: nil, bio: nil},
#   {first_name: "Zander", last_name: "Cormier", email: "zander.cormier@yahoo.com", phone_number: "884-948-9837", middle_name: nil, bio: nil},
#   {first_name: "Abigail", last_name: "Kuvalis", email: "abigail_kuvalis@yahoo.com", phone_number: "1-149-351-6641", middle_name: nil, bio: nil},
#   {first_name: "Chase", last_name: "Lesch", email: "chase.lesch@gmail.com", phone_number: "739-600-7822", middle_name: nil, bio: nil},
#   {first_name: "Orin", last_name: "Prosacco", email: "prosacco_orin@gmail.com", phone_number: "1-333-665-2674 x763", middle_name: nil, bio: nil},
#   {first_name: "Crystel", last_name: "Lang", email: "crystel_lang@hotmail.com", phone_number: "(358) 036-3514", middle_name: nil, bio: nil},
#   {first_name: "Louisa", last_name: "Greenholt", email: "greenholt.louisa@yahoo.com", phone_number: "711.344.0137 x882", middle_name: nil, bio: nil},
#   {first_name: "Jaeden", last_name: "Smith", email: "jaeden_smith@gmail.com", phone_number: "1-623-603-0299 x299", middle_name: nil, bio: nil},
#   {first_name: "Mya", last_name: "Pagac", email: "mya_pagac@hotmail.com", phone_number: "1-284-330-4608", middle_name: nil, bio: nil},
#   {first_name: "Rowland", last_name: "Ward", email: "rowland_ward@yahoo.com", phone_number: "223.525.4094 x063", middle_name: nil, bio: nil},
#   {first_name: "Lemuel", last_name: "Zulauf", email: "zulauf.lemuel@hotmail.com", phone_number: "113-998-9716", middle_name: nil, bio: nil},
#   {first_name: "Liana", last_name: "Leannon", email: "liana_leannon@hotmail.com", phone_number: "664-701-8912", middle_name: nil, bio: nil},
#   {first_name: "Candelario", last_name: "Farrell", email: "candelario_farrell@hotmail.com", phone_number: "1-468-055-0470", middle_name: nil, bio: nil},
#   {first_name: "Garrison", last_name: "Veum", email: "veum_garrison@yahoo.com", phone_number: "704.912.9480 x5094", middle_name: nil, bio: nil},
#   {first_name: "Hoyt", last_name: "Keeling", email: "keeling_hoyt@hotmail.com", phone_number: "267-786-4703 x1338", middle_name: nil, bio: nil},
#   {first_name: "Kristin", last_name: "Trantow", email: "trantow_kristin@hotmail.com", phone_number: "365.313.4104 x0252", middle_name: nil, bio: nil},
#   {first_name: "Clotilde", last_name: "Treutel", email: "clotilde.treutel@gmail.com", phone_number: "1-593-923-9620 x8423", middle_name: nil, bio: nil},
#   {first_name: "Bernadette", last_name: "Harris", email: "bernadette.harris@yahoo.com", phone_number: "(181) 875-0897", middle_name: nil, bio: nil},
#   {first_name: "Bethany", last_name: "VonRueden", email: "vonrueden.bethany@yahoo.com", phone_number: "510.018.8000 x064", middle_name: nil, bio: nil},
#   {first_name: "Grady", last_name: "Kris", email: "kris_grady@yahoo.com", phone_number: "(378) 937-5287 x563", middle_name: nil, bio: nil},
#   {first_name: "Hettie", last_name: "Dickens", email: "hettie_dickens@gmail.com", phone_number: "1-954-688-0636", middle_name: nil, bio: nil},
#   {first_name: "Sim", last_name: "Mante", email: "sim_mante@hotmail.com", phone_number: "591.305.3188", middle_name: nil, bio: nil},
#   {first_name: "Amalia", last_name: "Greenfelder", email: "amalia_greenfelder@hotmail.com", phone_number: "661.092.7971 x714", middle_name: nil, bio: nil},
#   {first_name: "Vita", last_name: "Cassin", email: "cassin.vita@hotmail.com", phone_number: "(810) 874-7575", middle_name: nil, bio: nil},
#   {first_name: "Lawrence", last_name: "Runolfsdottir", email: "lawrence_runolfsdottir@hotmail.com", phone_number: "665-875-1037 x91866", middle_name: nil, bio: nil},
#   {first_name: "Emma", last_name: "Abbott", email: "abbott.emma@yahoo.com", phone_number: "418.200.9662", middle_name: nil, bio: nil},
#   {first_name: "Aneta", last_name: "Gurba", email: "aneta@gmail.com", phone_number: "773 555 6666", middle_name: nil, bio: nil}
# ])

# Group.create!(name: "Friends")
# Group.create!(name: "Family")
# Group.create!(name: "Actualize")

contact_ids = Contact.pluck(:id)
group_ids = Group.pluck(:id)
contact_ids.each do |c_id|
  selected_group_ids = group_ids.sample(rand(1..3))
  selected_group_ids.each do |g_id|
    ContactGroup.create!(contact_id: c_id, group_id: g_id)
  end
end
